//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated to match HRDepartment.aspx markup.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRModule {

    public partial class HRDepartment {

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// lblNavUser control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNavUser;

        /// <summary>
        /// pnlMsg control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlMsg;

        /// <summary>
        /// litFormHeading control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litFormHeading;

        /// <summary>
        /// hfDeptID control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfDeptID;

        /// <summary>
        /// txtCode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCode;

        /// <summary>
        /// txtName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtName;

        /// <summary>
        /// chkActive control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkActive;

        /// <summary>
        /// btnSave control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSave;

        /// <summary>
        /// btnClear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnClear;

        /// <summary>
        /// gvDepts control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvDepts;
    }
}
