//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated to match HREmployeeImport.aspx markup.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRModule {

    public partial class HREmployeeImport {

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// lblNavUser control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNavUser;

        /// <summary>
        /// pnlMsg control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlMsg;

        /// <summary>
        /// fuFile control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload fuFile;

        /// <summary>
        /// btnUpload control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnUpload;

        /// <summary>
        /// chkAutoCreateDept control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkAutoCreateDept;

        /// <summary>
        /// hfFilePath control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfFilePath;

        /// <summary>
        /// pnlResults control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlResults;

        /// <summary>
        /// litTotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTotal;

        /// <summary>
        /// litOK control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litOK;

        /// <summary>
        /// litWarn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litWarn;

        /// <summary>
        /// litErr control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litErr;

        /// <summary>
        /// gvPreview control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvPreview;

        /// <summary>
        /// btnConfirm control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConfirm;

        /// <summary>
        /// btnReset control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnReset;
    }
}
