//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated to match HREmployee.aspx markup.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRModule {

    public partial class HREmployee {

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// lblNavUser control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNavUser;

        /// <summary>
        /// btnNew control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnNew;

        /// <summary>
        /// pnlMsg control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlMsg;

        /// <summary>
        /// pnlList control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlList;

        /// <summary>
        /// txtSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        /// <summary>
        /// ddlFilterDept control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterDept;

        /// <summary>
        /// chkActiveOnly control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkActiveOnly;

        /// <summary>
        /// btnSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSearch;

        /// <summary>
        /// gvEmployees control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvEmployees;

        /// <summary>
        /// pnlEdit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlEdit;

        /// <summary>
        /// litFormHeading control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litFormHeading;

        /// <summary>
        /// hfEmployeeID control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfEmployeeID;

        /// <summary>
        /// txtCode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCode;

        /// <summary>
        /// txtName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtName;

        /// <summary>
        /// txtFatherName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFatherName;

        /// <summary>
        /// ddlGender control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlGender;

        /// <summary>
        /// txtDOB control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDOB;

        /// <summary>
        /// txtDOJ control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDOJ;

        /// <summary>
        /// txtDOL control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDOL;

        /// <summary>
        /// chkActive control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkActive;

        /// <summary>
        /// ddlDept control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlDept;

        /// <summary>
        /// txtDesignation control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDesignation;

        /// <summary>
        /// ddlEmpType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlEmpType;

        /// <summary>
        /// txtMobile control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtMobile;

        /// <summary>
        /// txtAltMobile control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAltMobile;

        /// <summary>
        /// txtEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>
        /// txtPincode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPincode;

        /// <summary>
        /// txtCity control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCity;

        /// <summary>
        /// txtState control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtState;

        /// <summary>
        /// txtAddress control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAddress;

        /// <summary>
        /// txtAadhaar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAadhaar;

        /// <summary>
        /// txtPAN control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPAN;

        /// <summary>
        /// txtUAN control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtUAN;

        /// <summary>
        /// txtPF control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPF;

        /// <summary>
        /// txtESI control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtESI;

        /// <summary>
        /// txtBankAc control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBankAc;

        /// <summary>
        /// txtBankName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBankName;

        /// <summary>
        /// txtIFSC control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtIFSC;

        /// <summary>
        /// txtBasic control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBasic;

        /// <summary>
        /// txtHRA control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtHRA;

        /// <summary>
        /// txtConv control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtConv;

        /// <summary>
        /// txtOther control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtOther;

        /// <summary>
        /// txtGross control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtGross;

        /// <summary>
        /// btnSave control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSave;

        /// <summary>
        /// btnCancel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCancel;
    }
}
