//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated to match HRLogin.aspx markup.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRModule {

    public partial class HRLogin {

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// pnlError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlError;

        /// <summary>
        /// lblError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblError;

        /// <summary>
        /// txtUsername control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtUsername;

        /// <summary>
        /// txtPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        /// <summary>
        /// btnLogin control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnLogin;
    }
}
