//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated to match HROrgChart.aspx markup.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRModule {

    public partial class HROrgChart {

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// lblNavUser control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNavUser;
    }
}
