//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockApp
{
    public partial class ERPHome
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Label     lblUserName;
        protected global::System.Web.UI.WebControls.Label     lblUserRole;
    }
}
