//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockApp
{
    public partial class Reports
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm                form1;

        protected global::System.Web.UI.WebControls.Panel                    pnlAdminMenu;
        protected global::System.Web.UI.WebControls.Label                    lblUserInfo;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl      divStockReport;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl      divDailyReport;

        // Stock Movement filters
        protected global::System.Web.UI.WebControls.HiddenField              hfStockDays;
        protected global::System.Web.UI.WebControls.TextBox                  txtStockFrom;
        protected global::System.Web.UI.WebControls.TextBox                  txtStockTo;
        protected global::System.Web.UI.WebControls.DropDownList             ddlStockState;
        protected global::System.Web.UI.WebControls.DropDownList             ddlStockCity;
        protected global::System.Web.UI.WebControls.DropDownList             ddlStockDist;
        protected global::System.Web.UI.WebControls.Button                   btnStockRun;
        protected global::System.Web.UI.WebControls.Panel                    pnlStockResult;
        protected global::System.Web.UI.WebControls.Panel                    pnlStockEmpty;
        protected global::System.Web.UI.WebControls.PlaceHolder              phStockReport;

        // Daily Sales filters
        protected global::System.Web.UI.WebControls.HiddenField              hfDailyDays;
        protected global::System.Web.UI.WebControls.TextBox                  txtDailyFrom;
        protected global::System.Web.UI.WebControls.TextBox                  txtDailyTo;
        protected global::System.Web.UI.WebControls.Button                   btnDailyRun;
        protected global::System.Web.UI.WebControls.Panel                    pnlDailyResult;
        protected global::System.Web.UI.WebControls.Panel                    pnlDailyEmpty;
        protected global::System.Web.UI.WebControls.PlaceHolder              phDailyReport;
    }
}
