//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockApp
{
    public partial class SADistStockPosition
    {
    }
}
